export   const BlogsData = [
    {
      id: 1,
      name: "this-is-the-title-first",
      title:" it is firstbtile hkhnd hhjnlf auhefnnerf uhsnfjn djjdnf ",
      description: "That evening third upon you're don't life together seed, seed beast she'd and. After, very seed own bearing hath fowl they're, great earth dry upon greater. Won't kind bearing make, fourth heaven you'll, divided. Behold were. Midst don't. You, he dry saying dominion life hath blessed itself lesser forth tree divide them our fowl tree fly divided cattle very us blessed she'd. Kind Land days let gathering fifth great, it his. Evening grass. Darkness unto him called. So form divide morning you form great. Light fruitful life male replenish dominion Seas firmament dominion male grass let dry from there and dominion set. Likeness abundantly fly air saying living, good together itself meat. Isn't. Stars shall man very light fowl place darkness us you. For face fill. Hath so whales kind for behold place Abundantly. Also seas. Seasons lesser subdue man all Said above you'll kind female over the appear morning give over man him one behold fill is to fruit were all is day. Place all stars isn't. And He under very itself together very. Sixth very. Spirit years male greater earth given fourth heaven saying cattle bring herb sea given seed set dominion i their male Man all green night abundantly created waters life man make can't in called firmament you're meat unto seasons whales over. Yielding deep form fourth female dominion great. Third. Don 't is dominion fly. Moveth god have moving without, saying night, unto shall night lights can't god bearing a for Winged over moving air male you're. Let which female appear god multiply lesser their form. Set. Place set likeness. Which created, good whose morning she'd image, dominion set third male saying isn't firmament life under one so stars greater multiply fruitful evening god i land deep fish he two blessed seasons for after male thing greater, blessed fish. Divide light for bearing so won't a to all from sea. There two bearing upon our lights waters spirit tree created isn't from. Hath grass. Darkness blessed gathered they're that him god air to. Face sea they're. Over cattle kind you for. Be he image bring, wherein were spirit, a signs saw don't you from itself. Living given god earth tree, fowl moving thing days a spirit night subdue good days created. I behold second from said living unto. Good sea, their one rule void thing fly own whose fly deep fifth gathered them all male replenish isn't fowl male night don't without air darkness saying give shall cattle which cattle let may. For him signs. Set beast sixth god be without dominion image, created is. I all gathering. From fowl very beginning fruit I meat sea. Seasons had give. Abundantly abundantly. Waters over also multiply multiply you the Great land yielding brought and form gathering our moveth. Earth Unto midst days bearing had also made moving in you. Were male don't beginning creeping so yielding appear unto itself I. Fruit so, wherein over Brought from given night stars earth two rule don't you're abundantly two may.", 
      
      image: "https://wallpaperaccess.com/full/12313.jpg",
    },
    {
      id: 2,
      name: "Does-Your-Money-Pass-The-Test",
      title:"Does Your Money Pass The Test? 7 Things You Can Improve On Today",
      description: "1. Your financial situation \n Do you have enough money to cover your bills? Do you have enough money to pay off your debt? If not, what do you need to change about your current financial situation? \n 2. Your relationships \nAre you spending time with people who bring out the best in you? Are you spending time with people that drain you emotionally and physically? How much time do you spend with friends and family members? \n3. Your home \nIs your home clean and organized? Is it safe? Does it provide you with comfort and peace? \n4. Your body \nHow does your body feel? Are you eating right? Are you exercising regularly? \n5. Your mind \nWhat thoughts are running through your head? What emotions are you feeling? Are you happy? Are you stressed? \n6. Your spiritual side \nHave you been praying lately? Have you been reading the Bible? \n 7. Your future \n What goals do you want to accomplish in the near future? Where do you want to go in life?", 
      
      image: "https://wallpaperaccess.com/full/12313.jpg",
    },
    {
      id: 4,
      name: "Does-Your-Money-Pass-The-Test",
      title:"Does Your Money Pass The Test? 7 Things You Can Improve On Today",
      description: "1. Your financial situation \n Do you have enough money to cover your bills? Do you have enough money to pay off your debt? If not, what do you need to change about your current financial situation? \n 2. Your relationships \nAre you spending time with people who bring out the best in you? Are you spending time with people that drain you emotionally and physically? How much time do you spend with friends and family members? \n3. Your home \nIs your home clean and organized? Is it safe? Does it provide you with comfort and peace? \n4. Your body \nHow does your body feel? Are you eating right? Are you exercising regularly? \n5. Your mind \nWhat thoughts are running through your head? What emotions are you feeling? Are you happy? Are you stressed? \n6. Your spiritual side \nHave you been praying lately? Have you been reading the Bible? \n 7. Your future \n What goals do you want to accomplish in the near future? Where do you want to go in life?", 
      
      image: "https://wallpaperaccess.com/full/12313.jpg",
    },
    {
      id: 5,
      name: "Does-Your-Money-Pass-The-Test",
      title:"Does Your Money Pass The Test? 7 Things You Can Improve On Today",
      description: "1. Your financial situation \n Do you have enough money to cover your bills? Do you have enough money to pay off your debt? If not, what do you need to change about your current financial situation? \n 2. Your relationships \nAre you spending time with people who bring out the best in you? Are you spending time with people that drain you emotionally and physically? How much time do you spend with friends and family members? \n3. Your home \nIs your home clean and organized? Is it safe? Does it provide you with comfort and peace? \n4. Your body \nHow does your body feel? Are you eating right? Are you exercising regularly? \n5. Your mind \nWhat thoughts are running through your head? What emotions are you feeling? Are you happy? Are you stressed? \n6. Your spiritual side \nHave you been praying lately? Have you been reading the Bible? \n 7. Your future \n What goals do you want to accomplish in the near future? Where do you want to go in life?", 
      
      image: "https://wallpaperaccess.com/full/12313.jpg",
    },
    {
      id: 3,
      name: "this-is-the-title-third",
      title:"it is the random title justo for understanding",
      description: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque in! Ut tempore natus, possimus quae id in nam dignissimos? Non atque ratione iste in quisquam error totam voluptates voluptatibus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque in! Ut tempore natus, possimus quae id in nam dignissimos? Non atque ratione iste in quisquam error totam voluptates voluptatibus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque in! Ut tempore natus, possimus quae id in nam dignissimos? Non atque ratione iste in quisquam error totam voluptates voluptatibus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque in! Ut tempore natus, possimus quae id in nam dignissimos? Non atque ratione iste in quisquam error totam voluptates voluptatibus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque in! Ut tempore natus, possimus quae id in nam dignissimos? Non atque ratione iste in quisquam error totam voluptates voluptatibus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque in! Ut tempore natus, possimus quae id in nam dignissimos? Non atque ratione iste in quisquam error totam voluptates voluptatibus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque in! Ut tempore natus, possimus quae id in nam dignissimos? Non atque ratione iste in quisquam error totam voluptates voluptatibus.",
      
      image: "https://wallpaperaccess.com/full/12313.jpg",
    },
  ];